/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viggenere5iv7;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author porfi
 */
public class InterfazKawai extends javax.swing.JFrame {

    /**
     * Creates new form InterfazKawai
     */
    
    FondoPanel fondo = new FondoPanel();
    
    public InterfazKawai() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cambiar = new javax.swing.JButton();
        btn_decifrar = new javax.swing.JButton();
        txt_m = new javax.swing.JTextField();
        txt_r = new javax.swing.JTextField();
        btn_cifrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_c = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cambiar.setText("Cambiar");
        btn_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiarActionPerformed(evt);
            }
        });

        btn_decifrar.setText("Decifrar");
        btn_decifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decifrarActionPerformed(evt);
            }
        });

        txt_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mActionPerformed(evt);
            }
        });

        txt_r.setEnabled(false);

        btn_cifrar.setText("Cifrar");
        btn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Mensaje");

        jLabel2.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(txt_r, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cambiar))
                            .addComponent(txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btn_cifrar)
                .addGap(94, 94, 94)
                .addComponent(btn_decifrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cambiar)
                    .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_decifrar)
                    .addComponent(btn_cifrar))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mActionPerformed

    private void btn_decifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decifrarActionPerformed
        // TODO add your handling code here:
        String txt_cifrado = txt_m.getText().toUpperCase();
        String clave = txt_c.getText().toUpperCase();
        
        Vigikawaii vk = new Vigikawaii();
        
        Validar val = new Validar();
        boolean check = val.letras(txt_cifrado);
       
        boolean check_c = val.letras(clave);
        
        if (clave.length() > txt_cifrado.length()) {
            JOptionPane.showMessageDialog(null, "La clave no puede tener una cantidad de caracteres mayor a el mensaje");
        }else{
            if (txt_cifrado == null || clave == null ) {
                JOptionPane.showMessageDialog(null, "Llene los campos 'mensaje' y 'clave'.");
            }else if(check && clave == null){
                 JOptionPane.showMessageDialog(null, "Llene el campo'clave'.");
            }else if(check && check_c){

                String resultado = vk.desencriptarTextoClaro(txt_cifrado.replace(" ", ""), clave.replace(" ", ""));

                txt_r.setText(resultado);

            }
        }
    }//GEN-LAST:event_btn_decifrarActionPerformed

    private void btn_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiarActionPerformed
        // TODO add your handling code here:
        String m = txt_m.getText();
        String r = txt_r.getText();
        
        txt_m.setText(r);
        txt_r.setText("");
    }//GEN-LAST:event_btn_cambiarActionPerformed

    private void btn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarActionPerformed
        // TODO add your handling code here:
        
        String txt_claro = txt_m.getText().toUpperCase();
        String clave = txt_c.getText().toUpperCase();
        
        Vigikawaii vk = new Vigikawaii();
        Validar val = new Validar();
        boolean check = val.letras(txt_claro);
        boolean check_c = val.letras(clave);
        
        if (clave.length() > txt_claro.length()) {
            JOptionPane.showMessageDialog(null, "La clave no puede tener una cantidad de caracteres mayor a el mensaje");
        }else{
            if (txt_claro == null || clave == null ) {
            JOptionPane.showMessageDialog(null, "Llene los campos 'mensaje' y 'clave'.");
            }else if(check && clave == null){
                 JOptionPane.showMessageDialog(null, "Llene el campo'clave'.");
            }else if(check && check_c){

                String resultado = vk.encriptarTextoClaro(txt_claro.replace(" ", ""), clave.replace(" ", ""));

                txt_r.setText(resultado);

            }
        }
    }//GEN-LAST:event_btn_cifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazKawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazKawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazKawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazKawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazKawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar;
    private javax.swing.JButton btn_cifrar;
    private javax.swing.JButton btn_decifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_c;
    private javax.swing.JTextField txt_m;
    private javax.swing.JTextField txt_r;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
    
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
        
            imagen = new ImageIcon(getClass().getResource("/img/kawai.gif")).getImage();
        
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
            
        }
    
    }

}
